stages:
    - syntax
    - build
    - test
    - stage
    - prod

unit test:
    stage: syntax
    script:
        - echo "test 1"
        
linter:
    stage: syntax
    script:
        - echo "test 2"
      
type test:
    stage: syntax
    script:
        - echo "test 3"

build:
    stage: build
    script:
        - ./build.sh

autotest:
   stage: test
   script: "echo autotest ready"

selenium:
   stage: test
   script: "echo selenium ready"

deploy to stage:
  stage: stage
  script:
        - ./deploy.sh

prod:
  stage: prod
  script:
        - ./deploy.sh
    when: manual