stages:
    - syntax
    - build
    - test
    - stage
    - prod

unit test:
    stage: syntax
    script:
        - echo "test 1 ------------"
        
linter:
    stage: syntax
    script:
        - echo "test 2 ------------"
      
type test:
    stage: syntax
    script:
        - echo "test 3 -----------"

build:
    stage: build
    script:
        - echo 'running ./build.sh'

autotest:
   stage: test
   script: "echo autotest ready"

selenium:
   stage: test
   script: "echo selenium ready"

deploy website:
  stage: stage
  script:
        - cp -rf ./html/* /var/www/html
        - zip -r app_archive.zip ../ ; cp -rf ./app_archive.zip /var/www/html/app_archive.zip ./html
  when: manual
  tags:
        - stage-shell
  only:
    refs:
        - tag
        - main
        - /ˆˆrelease.*$/

deploy to prod:
  stage: prod
  script:
        - ./deploy.sh
  only:
    refs:
        - tag
        - main
        - /ˆˆrelease.*$/
  when: manual
